CREATE TABLE "T_USER" 
(	
	"USER_ID" VARCHAR2(5) NOT NULL ENABLE, 
	"USER_PASS" VARCHAR2(100), 
	"USER_NAME" VARCHAR2(50), 
	"HOSPITAL_ID" VARCHAR2(5), 
	"KENGEN_CD" VARCHAR2(5), 
	"SUBMIT_USER_ID" VARCHAR2(5), 
	"SUBMIT_YMD" DATE, 
	"UPDATE_YMD" DATE, 
	"DELETE_YMD" DATE, 
	CONSTRAINT "T_USER" PRIMARY KEY ("USER_ID")
);

CREATE TABLE "T_KENGEN" 
(	
	"CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20), 
	CONSTRAINT "T_KENGEN" PRIMARY KEY ("CODE")
);

CREATE TABLE "T_HOSPITAL" 
(	
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	CONSTRAINT "T_SYOZOKU" PRIMARY KEY ("ID")
);

CREATE TABLE "T_CHART" 
(
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
    	"PATIENT_ID" VARCHAR2(5) NOT NULL ENABLE,
    	"DOCTOR_ID" VARCHAR2(5) NOT NULL ENABLE,
    	"YMD" DATE,
    	"SYMPTOMS" VARCHAR2(50),
    	"PART" VARCHAR2(50),
    	"DISEASENAME" VARCHAR2(50),
    	"DETAILS" VARCHAR2(200),
    	"HOSPITAL_ID" VARCHAR2(5),
	CONSTRAINT "T_CHART" PRIMARY KEY ("ID")
);

CREATE TABLE "T_DOCTOR" 
(
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50),
	"HOSPITAL_ID" VARCHAR2(5), 
	"DEPARTMENT_CD" VARCHAR2(5),
	"GENDER" VARCHAR2(2),
	"AGE" NUMBER,
	CONSTRAINT "T_DOCTOR" PRIMARY KEY ("ID")
);

CREATE TABLE "T_DEPARTMENT" 
(	
	"CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20), 
	"HOSPITAL_ID" VARCHAR2(5),
	CONSTRAINT "T_DEPARTMENT" PRIMARY KEY ("CODE")
);

CREATE TABLE "T_PATIENT" 
(
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50),
	"BIRTHDAY" DATE,
	"GENDER" VARCHAR2(2),
	"AGE" NUMBER,
	"BLOODTYPE" VARCHAR2(10),
	"ADDRESS" VARCHAR2(100),
	"TEL" VARCHAR2(20),
	"ALLERGY" VARCHAR2(100),
	"MEDICALHISTORY" VARCHAR2(300),
	"PREGNANCY" VARCHAR2(100),
	CONSTRAINT "T_PATIENT" PRIMARY KEY ("ID")
);