//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CHART
    {
        public string ID { get; set; }
        public string PATIENT_ID { get; set; }
        public string DOCTOR_ID { get; set; }
        public Nullable<System.DateTime> YMD { get; set; }
        public string SYMPTOMS { get; set; }
        public string PART { get; set; }
        public string DISEASENAME { get; set; }
        public string DETAILS { get; set; }
        public string HOSPITAL_ID { get; set; }
    
        public virtual T_DOCTOR T_DOCTOR { get; set; }
        public virtual T_PATIENT T_PATIENT { get; set; }
    }
}
