//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GIFTITEMLIST
    {
        public string ID { get; set; }
        public string TITLE { get; set; }
        public string REGISTUSERID { get; set; }
        public string CATEGORYID { get; set; }
        public string SUBCATEGORYID { get; set; }
        public string ISDONE { get; set; }
        public string GIVEID { get; set; }
        public string DETAILS { get; set; }
        public string PASS { get; set; }
        public string EXPLANATION { get; set; }
    }
}
