//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUESTIONNAIRE
    {
        public string ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> TIMELIMIT { get; set; }
        public string GENRE { get; set; }
        public string CREATEID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string ANSWER { get; set; }
    }
}
