//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USER_ID { get; set; }
        public string USER_PASS { get; set; }
        public string USER_NAME { get; set; }
        public string HOSPITAL_ID { get; set; }
        public string KENGEN_CD { get; set; }
        public string SUBMIT_USER_ID { get; set; }
        public Nullable<System.DateTime> SUBMIT_YMD { get; set; }
        public Nullable<System.DateTime> UPDATE_YMD { get; set; }
        public Nullable<System.DateTime> DELETE_YMD { get; set; }
    
        public virtual T_HOSPITAL T_HOSPITAL { get; set; }
        public virtual T_KENGEN T_KENGEN { get; set; }
    }
}
